export const ActionTypes = {
    UPDATE_NAME: 'UPDATE_NAME',
    FETCH_USER_NAME: 'FETCH_USER_NAME',
    FETCH_USER_NAME_SUCCESS: 'FETCH_USER_NAME_SUCCESS',
    FETCH_USER_NAME_FAILURE: 'FETCH_USER_NAME_FAILURE'
};